In [25]:
# 1. Result calculator

def calc_score(marks):
  result = ""
  if marks < 40:
    result += "Fail"
  else:
    result += "Pass"
  return result

s_marks = 30
print(calc_score(s_marks))

Fail

In [26]:
# 2. Numpy functions

import numpy as np

arr = np.array([32,46,50])
print(arr)
print(arr.shape)

matrix = np.array([
    [10,20,30],
    [40,50,60],
    [2,3,4]
])
print(matrix)
print(matrix.shape)
print(matrix[0])

print(matrix[:,0])
print(matrix[1:4,1:4])

[32 46 50]
(3,)
[[10 20 30]
 [40 50 60]
 [ 2  3  4]]
(3, 3)
[10 20 30]
[10 40  2]
[[50 60]
 [ 3  4]]

In [27]:
# 3. Rule-based filtering

marks = np.array([78,91,55,72,40,88])

print(marks>70)

high_scorers = marks[marks>70]
print(high_scorers)


print(marks[(marks>=60) & (marks <= 90)])

[ True  True False  True False  True]
[78 91 72 88]
[78 72 88]

In [28]:
# 4. Converting array to 2-d matrix

import numpy as np
marks = np.array([78,91,55,72,40,88])
marks_2d = marks.reshape(3, 2)
print(marks_2d)
print(marks_2d.max())

[[78 91]
 [55 72]
 [40 88]]
91

In [29]:
# 5. Dealing with data!

import pandas as pd

df = pd.read_csv("/content/session4_dummy_students_data.csv (2).xls")
print(df)

    student_id    name  age     city  math  science  english  \
0          101   Aarav   16   Mumbai    78       84       69
1          102    Diya   16    Delhi    91       88       94
2          103   Kabir   17  Mathura    55       61       58
3          104   Meera   16    Noida    72       79       81
4          105   Rohan   17   Mumbai    40       52       47
5          106    Sara   16    Delhi    88       93       90
6          107  Ishaan   17  Mathura    64       70       66
7          108  Ananya   16    Noida    95       92       89
8          109  Vivaan   17   Mumbai    48       57       51
9          110    Tara   16    Delhi    83       76       85
10         111   Arjun   17  Mathura    67       63       72
11         112   Nisha   16    Noida    74       81       79
12         113     Dev   17   Mumbai    35       45       42
13         114   Priya   16    Delhi    89       86       91
14         115   Kunal   17  Mathura    58       54       60
15         116    Riya   16    Noida    92       90       96
16         117      Om   17   Mumbai    61       69       65
17         118   Aditi   16    Delhi    80       85       83
18         119    Yash   17  Mathura    43       49       46
19         120   Sneha   16    Noida    77       73       80

    attendance_percent  study_hours_per_week  assignments_submitted  \
0                   92                     8                      9
1                   96                    11                     10
2                   75                     5                      6
3                   89                     7                      8
4                   68                     3                      5
5                   97                    10                     10
6                   82                     6                      7
7                   94                    12                     10
8                   71                     4                      6
9                   90                     9                      9
10                  80                     6                      8
11                  88                     8                      8
12                  62                     2                      4
13                  95                    10                     10
14                  77                     5                      6
15                  98                    13                     10
16                  79                     6                      7
17                  91                     9                      9
18                  66                     3                      5
19                  87                     8                      8

    final_project_score
0                    82
1                    93
2                    60
3                    78
4                    45
5                    95
6                    69
7                    91
8                    55
9                    86
10                   70
11                   80
12                   39
13                   92
14                   63
15                   96
16                   68
17                   84
18                   48
19                   79

In [30]:
# Convert science column to numpy

science_scores = df["science"].to_numpy()
print(science_scores)
print(type(science_scores))
print(science_scores.max())

[84 88 61 79 52 93 70 92 57 76 63 81 45 86 54 90 69 85 49 73]
<class 'numpy.ndarray'>
93

In [31]:
# To calculate average of marks of students

avg = df[["math","science","english"]].to_numpy()
print(avg.mean())

df["average"] = avg.mean(axis=1)
print(df[["name","average"]])

71.35
      name    average
0    Aarav  77.000000
1     Diya  91.000000
2    Kabir  58.000000
3    Meera  77.333333
4    Rohan  46.333333
5     Sara  90.333333
6   Ishaan  66.666667
7   Ananya  92.000000
8   Vivaan  52.000000
9     Tara  81.333333
10   Arjun  67.333333
11   Nisha  78.000000
12     Dev  40.666667
13   Priya  88.666667
14   Kunal  57.333333
15    Riya  92.666667
16      Om  65.000000
17   Aditi  82.666667
18    Yash  46.000000
19   Sneha  76.666667

In [32]:
# Rule-based filtering

stud = df[ df["average"]>= 85]
print(stud[["name","average"]])
print()
mathura_students = df[df["city"] == "Mathura"]
print(mathura_students[["name", "city", "average"]])
print()
attendance = df[df["attendance_percent"] < 75]
print(attendance[["name","attendance_percent"]])

      name    average
1     Diya  91.000000
5     Sara  90.333333
7   Ananya  92.000000
13   Priya  88.666667
15    Riya  92.666667

      name     city    average
2    Kabir  Mathura  58.000000
6   Ishaan  Mathura  66.666667
10   Arjun  Mathura  67.333333
14   Kunal  Mathura  57.333333
18    Yash  Mathura  46.000000

      name  attendance_percent
4    Rohan                  68
8   Vivaan                  71
12     Dev                  62
18    Yash                  66

In [33]:
import pandas as pd
import numpy as np

# Read session4_dummy_students_data.csv

df = pd.read_csv("/content/session4_dummy_students_data.csv (2).xls")
print(df)

    student_id    name  age     city  math  science  english  \
0          101   Aarav   16   Mumbai    78       84       69
1          102    Diya   16    Delhi    91       88       94
2          103   Kabir   17  Mathura    55       61       58
3          104   Meera   16    Noida    72       79       81
4          105   Rohan   17   Mumbai    40       52       47
5          106    Sara   16    Delhi    88       93       90
6          107  Ishaan   17  Mathura    64       70       66
7          108  Ananya   16    Noida    95       92       89
8          109  Vivaan   17   Mumbai    48       57       51
9          110    Tara   16    Delhi    83       76       85
10         111   Arjun   17  Mathura    67       63       72
11         112   Nisha   16    Noida    74       81       79
12         113     Dev   17   Mumbai    35       45       42
13         114   Priya   16    Delhi    89       86       91
14         115   Kunal   17  Mathura    58       54       60
15         116    Riya   16    Noida    92       90       96
16         117      Om   17   Mumbai    61       69       65
17         118   Aditi   16    Delhi    80       85       83
18         119    Yash   17  Mathura    43       49       46
19         120   Sneha   16    Noida    77       73       80

    attendance_percent  study_hours_per_week  assignments_submitted  \
0                   92                     8                      9
1                   96                    11                     10
2                   75                     5                      6
3                   89                     7                      8
4                   68                     3                      5
5                   97                    10                     10
6                   82                     6                      7
7                   94                    12                     10
8                   71                     4                      6
9                   90                     9                      9
10                  80                     6                      8
11                  88                     8                      8
12                  62                     2                      4
13                  95                    10                     10
14                  77                     5                      6
15                  98                    13                     10
16                  79                     6                      7
17                  91                     9                      9
18                  66                     3                      5
19                  87                     8                      8

    final_project_score
0                    82
1                    93
2                    60
3                    78
4                    45
5                    95
6                    69
7                    91
8                    55
9                    86
10                   70
11                   80
12                   39
13                   92
14                   63
15                   96
16                   68
17                   84
18                   48
19                   79

In [34]:
# Create an average column using math, science, and english.

avg = df[["math","science","english"]].to_numpy()
df["average"] = avg.mean(axis=1)
print(df.head())

   student_id   name  age     city  math  science  english  \
0         101  Aarav   16   Mumbai    78       84       69
1         102   Diya   16    Delhi    91       88       94
2         103  Kabir   17  Mathura    55       61       58
3         104  Meera   16    Noida    72       79       81
4         105  Rohan   17   Mumbai    40       52       47

   attendance_percent  study_hours_per_week  assignments_submitted  \
0                  92                     8                      9
1                  96                    11                     10
2                  75                     5                      6
3                  89                     7                      8
4                  68                     3                      5

   final_project_score    average
0                   82  77.000000
1                   93  91.000000
2                   60  58.000000
3                   78  77.333333
4                   45  46.333333

In [35]:
# Create a result column: Pass if average >= 40, otherwise Fail.

df["result"] = np.where(df["average"] >= 40, "Pass", "Fail")
df.head()

,student_id,name,age,city,math,science,english,attendance_percent,study_hours_per_week,assignments_submitted,final_project_score,average,result
0,101,Aarav,16,Mumbai,78,84,69,92,8,9,82,77.000000,Pass
1,102,Diya,16,Delhi,91,88,94,96,11,10,93,91.000000,Pass
2,103,Kabir,17,Mathura,55,61,58,75,5,6,60,58.000000,Pass
3,104,Meera,16,Noida,72,79,81,89,7,8,78,77.333333,Pass
4,105,Rohan,17,Mumbai,40,52,47,68,3,5,45,46.333333,Pass

In [36]:
# Print class average.

class_avg = df["average"].mean()
print(class_avg)

71.35000000000001

In [37]:
# Print highest average and lowest average.

highest_avg = df["average"].max()
lowest_avg = df["average"].min()
print(highest_avg)
print(lowest_avg)

92.66666666666667
40.666666666666664

In [38]:
# Print top student or students.

top_students = df[df["average"] == highest_avg]
print(top_students["name"])

15    Riya
Name: name, dtype: object

In [39]:
# Print students with attendance below 75.

attendance = df[df["attendance_percent"] < 75]
print(attendance["name"])

4      Rohan
8     Vivaan
12       Dev
18      Yash
Name: name, dtype: object

In [40]:
# Print students who submitted fewer than 6 assignments.

assignment = df[df["assignments_submitted"] < 6]
print(assignment["name"])

4     Rohan
12      Dev
18     Yash
Name: name, dtype: object

In [41]:
# Save final output as session4_student_report.csv

df.to_csv("session4_student_report.csv", index=False)

In [52]:
# 6. Today's target -

import pandas as pd
import numpy as np

df = pd.read_csv("/content/session4_dummy_students_data.csv (2).xls")

# Find the average final_project_score.

avg_project_score = df["final_project_score"].mean()

print("Average Final_Project_Score:", avg_project_score)

Average Final_Project_Score: 73.65

In [43]:
# Find students with study_hours_per_week > 8.

study_hrs = df[df["study_hours_per_week"] > 8]
print(study_hrs[["name","study_hours_per_week"]])

      name  study_hours_per_week
1     Diya                    11
5     Sara                    10
7   Ananya                    12
9     Tara                     9
13   Priya                    10
15    Riya                    13
17   Aditi                     9

In [48]:
# Compare average marks of Mumbai students and Pune students

mumbai = df[df["city"]=="Mumbai"]
mumbai_avg = mumbai["average"].mean()

pune = df[df["city"]=="Pune"]
pune_avg = pune["average"].mean()

print("Average marks of Mumbai students:", mumbai_avg)
print("Average marks of Pune students:", pune_avg)

if len(mumbai) == 0 or len(pune) == 0:
  print("Sorry, we cannot compare!")
elif mumbai_avg > pune_avg:
  print("Mumbai students have higher average marks.")
else:
  print("Pune students have higher average marks.")

Average marks of Mumbai students: 56.2
Average marks of Pune students: nan
Sorry, we cannot compare!

In [49]:
# Create a new column called performance_level

df["performance_level"] = df["average"].apply(lambda x: "High" if x >= 75 else "Low")
df.head()

,student_id,name,age,city,math,science,english,attendance_percent,study_hours_per_week,assignments_submitted,final_project_score,average,performance_level
0,101,Aarav,16,Mumbai,78,84,69,92,8,9,82,77.000000,High
1,102,Diya,16,Delhi,91,88,94,96,11,10,93,91.000000,High
2,103,Kabir,17,Mathura,55,61,58,75,5,6,60,58.000000,Low
3,104,Meera,16,Noida,72,79,81,89,7,8,78,77.333333,High
4,105,Rohan,17,Mumbai,40,52,47,68,3,5,45,46.333333,Low

In [50]:
# Save only selected columns to a new CSV

selected = df[["student_id", "name", "attendance_percent", "average","performance_level"]]
print(selected)

    student_id    name  attendance_percent    average performance_level
0          101   Aarav                  92  77.000000              High
1          102    Diya                  96  91.000000              High
2          103   Kabir                  75  58.000000               Low
3          104   Meera                  89  77.333333              High
4          105   Rohan                  68  46.333333               Low
5          106    Sara                  97  90.333333              High
6          107  Ishaan                  82  66.666667               Low
7          108  Ananya                  94  92.000000              High
8          109  Vivaan                  71  52.000000               Low
9          110    Tara                  90  81.333333              High
10         111   Arjun                  80  67.333333               Low
11         112   Nisha                  88  78.000000              High
12         113     Dev                  62  40.666667               Low
13         114   Priya                  95  88.666667              High
14         115   Kunal                  77  57.333333               Low
15         116    Riya                  98  92.666667              High
16         117      Om                  79  65.000000               Low
17         118   Aditi                  91  82.666667              High
18         119    Yash                  66  46.000000               Low
19         120   Sneha                  87  76.666667              High